### ISSUE TITLE
Build fail - missing script: build:css

### ISSUE THREAD

**Issue by darrensw777** [yingray/create-react-redux-app#4]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Joanne\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@4.6.1
3 info using node@v6.10.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle create-react-redux-app@1.0.0~prestart: create-react-redux-app@1.0.0
6 silly lifecycle create-react-redux-app@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle create-react-redux-app@1.0.0~start: create-react-redux-app@1.0.0
8 verbose lifecycle create-react-redux-app@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle create-react-redux-app@1.0.0~start: PATH: C:\Users\Joanne\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;E:\design and photos\repos\create-react-redux\node_modules\.bin;C:\Users\Joanne\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Joanne\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP;C:\Program Files\Git\cmd;E:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;C:\Users\Joanne\AppData\Roaming\Composer\vendor\bin;C:\Users\Joanne\AppData\Local\Microsoft\WindowsApps;C:\Users\Joanne\AppData\Local\atom\bin;C:\Program Files\Atom\resources\app\apm\node_modules\atom-package-manager\bin;C:\Users\Joanne\AppData\Local\Microsoft\WindowsApps;C:\Users\Joanne\AppData\Roaming\npm;E:\xampp\mysql\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle create-react-redux-app@1.0.0~start: CWD: E:\design and photos\repos\create-react-redux
11 silly lifecycle create-react-redux-app@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build:css; (npm run watch:css & react-scripts start)' ]
12 silly lifecycle create-react-redux-app@1.0.0~start: Returned: code: 255  signal: null
13 info lifecycle create-react-redux-app@1.0.0~start: Failed to exec start script

************************************ see below ***************************************************
14 verbose stack Error: create-react-redux-app@1.0.0 start: `npm run build:css; (npm run watch:css & react-scripts start)`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Joanne\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Joanne\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid create-react-redux-app@1.0.0
16 verbose cwd E:\design and photos\repos\create-react-redux
17 verbose Windows_NT 10.0.16299
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Joanne\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v6.10.3
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 255
23 error create-react-redux-app@1.0.0 start: `npm run build:css; (npm run watch:css & react-scripts start)`
23 error Exit status 255
24 error Failed at the create-react-redux-app@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 255, true ]

**Comment by yingray** [comment]
Thanks for providing the issue.

It might be the special case on Windows. I just updated the script, ` npm run build:css; (npm run watch:css & react-scripts start)` to ` npm run build:css && (npm run watch:css & react-scripts start)`, than it works on Windows! 👍 

You might pull the repo latest version, upgrade npm package, and then try this working or not. Thanks. 😄
